# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 17:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='siren',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)]),
            preserve_default=False,
        ),
    ]
