# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20171210_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showing',
            old_name='dt',
            new_name='schedule',
        ),
    ]
